services: 

  pgsql-db:
    container_name: portfolio-db
    image: postgres:18.1
    shm_size: 1024mb
    restart: always
    ports:
      - "127.0.0.1:5432:5432" # bind to Host Machine
      # - 5432:5432 # bind to 0.0.0.0
    volumes:
      - pgsql_portfolio:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: party
  
  redis-db:
    container_name: redis-db
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6379:6379" # bind to Host Machine
      # - 6379:6379 # bind to 0.0.0.0

  server-py:
    container_name: server-py
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend:/server
    env_file:
      - ./backend/.env
    depends_on:
      - pgsql-db

  frontend:
    container_name: portfolio-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm run dev -- --host
    ports:
      - "127.0.0.1:5173:5173" # bind to Host Machine
      # - 5173:5173 # bind to 0.0.0.0
    
volumes:
  pgsql_portfolio:

