"""Added tempfs-related tables

Revision ID: 0ba004466179
Revises: ff62ee008645
Create Date: 2026-04-06 01:02:42.371565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ba004466179'
down_revision: Union[str, Sequence[str], None] = 'ff62ee008645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expired_file',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), nullable=False),
    sa.Column('original_size', sa.BIGINT(), nullable=False),
    sa.Column('stored_size', sa.BIGINT(), nullable=False),
    sa.Column('is_compressed', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('download_permission', sa.Enum('public', 'self', 'password', name='download_permission_enum'), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('temp_file',
    sa.Column('file_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), nullable=False),
    sa.Column('original_size', sa.BIGINT(), nullable=False),
    sa.Column('stored_size', sa.BIGINT(), nullable=False),
    sa.Column('is_compressed', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('download_permission', sa.Enum('public', 'self', 'password', name='download_permission_enum'), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_temp_file_expires_at'), 'temp_file', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_file_expires_at'), table_name='temp_file')
    op.drop_table('temp_file')
    op.drop_table('expired_file')
    # ### end Alembic commands ###