"""Update schema to allow grouping of topics

Revision ID: 36d23dffa78b
Revises: dbf6e01bd472
Create Date: 2026-03-31 10:05:35.834859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36d23dffa78b'
down_revision: Union[str, Sequence[str], None] = 'dbf6e01bd472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_group',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('topic', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.add_column('topic', sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('topic', sa.Column('last_thread_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'topic', 'thread', ['last_thread_id'], ['thread_id'])
    op.create_foreign_key(None, 'topic', 'topic_group', ['group_id'], ['group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'last_thread_id')
    op.drop_column('topic', 'last_activity_at')
    op.drop_column('topic', 'group_id')
    op.drop_table('topic_group')
    # ### end Alembic commands ###