"""Create tables for forum

Revision ID: 58fac84c1e22
Revises: ed0f086f7609
Create Date: 2026-03-30 13:41:37.471983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58fac84c1e22'
down_revision: Union[str, Sequence[str], None] = 'ed0f086f7609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('icon_url', sa.VARCHAR(), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('thread_count', sa.INTEGER(), nullable=False),
    sa.Column('reply_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thread',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), nullable=False),
    sa.Column('pin_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('reply_count', sa.INTEGER(), nullable=False),
    sa.Column('upvote_count', sa.INTEGER(), nullable=False),
    sa.Column('downvote_count', sa.INTEGER(), nullable=False),
    sa.Column('view_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_id.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('reply',
    sa.Column('reply_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('parent_reply_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('upvote_count', sa.INTEGER(), nullable=False),
    sa.Column('downvote_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_id.id'], ),
    sa.ForeignKeyConstraint(['parent_reply_id'], ['reply.reply_id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.thread_id'], ),
    sa.PrimaryKeyConstraint('reply_id')
    )
    op.create_table('thread_vote',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('is_upvote', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.thread_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'thread_id')
    )
    op.create_table('reply_attachment',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('reply_id', sa.Uuid(), nullable=False),
    sa.Column('attachment_type', sa.Enum('image', 'hyperlink', name='attachment_type'), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.reply_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('reply_vote',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reply_id', sa.Uuid(), nullable=False),
    sa.Column('is_upvote', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.reply_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'reply_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_vote')
    op.drop_table('reply_attachment')
    op.drop_table('thread_vote')
    op.drop_table('reply')
    op.drop_table('thread')
    op.drop_table('topic')
    # ### end Alembic commands ###