"""redefine SQL model to have server autogenerate values, not python

Revision ID: 63c181282826
Revises: 7b3332c5d429
Create Date: 2026-04-01 21:24:52.939192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63c181282826'
down_revision: Union[str, Sequence[str], None] = '7b3332c5d429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'thread', 'reply', ['last_activity'], ['reply_id'])
    op.create_foreign_key(None, 'topic', 'thread', ['last_thread_id'], ['thread_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_constraint(None, 'thread', type_='foreignkey')
    # ### end Alembic commands ###