"""update schema to drop columns that are joined in instead

Revision ID: 6df7fbb80e67
Revises: 6e6ec45e225e
Create Date: 2026-04-01 19:24:02.634847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df7fbb80e67'
down_revision: Union[str, Sequence[str], None] = '6e6ec45e225e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reply_auther_username_fkey'), 'reply', type_='foreignkey')
    op.drop_column('reply', 'auther_username')
    op.add_column('thread', sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('thread', sa.Column('last_activity', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_thread_last_activity_at'), 'thread', ['last_activity_at'], unique=False)
    op.drop_constraint(op.f('thread_auther_username_fkey'), 'thread', type_='foreignkey')
    op.create_foreign_key(None, 'thread', 'reply', ['last_activity'], ['reply_id'])
    op.drop_column('thread', 'auther_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('auther_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.create_foreign_key(op.f('thread_auther_username_fkey'), 'thread', 'user', ['auther_username'], ['username'])
    op.drop_index(op.f('ix_thread_last_activity_at'), table_name='thread')
    op.drop_column('thread', 'last_activity')
    op.drop_column('thread', 'last_activity_at')
    op.add_column('reply', sa.Column('auther_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('reply_auther_username_fkey'), 'reply', 'user', ['auther_username'], ['username'])
    # ### end Alembic commands ###