"""drop unused tables & columns

Revision ID: 6e6ec45e225e
Revises: 36d23dffa78b
Create Date: 2026-04-01 00:11:56.479144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e6ec45e225e'
down_revision: Union[str, Sequence[str], None] = '36d23dffa78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_attachment')
    op.add_column('reply', sa.Column('auther_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'reply', 'user', ['auther_username'], ['username'])
    op.drop_column('reply_vote', 'created_at')
    op.add_column('thread', sa.Column('auther_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'thread', 'user', ['auther_username'], ['username'])
    op.drop_column('thread_vote', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_vote', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.drop_column('thread', 'auther_username')
    op.add_column('reply_vote', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_column('reply', 'auther_username')
    op.create_table('reply_attachment',
    sa.Column('attachment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reply_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attachment_type', postgresql.ENUM('image', 'hyperlink', name='attachment_type'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.reply_id'], name=op.f('reply_attachment_reply_id_fkey')),
    sa.PrimaryKeyConstraint('attachment_id', name=op.f('reply_attachment_pkey'))
    )
    # ### end Alembic commands ###