"""fixed circular fk in Topic and Thread table for ...last_id

Revision ID: 7b3332c5d429
Revises: 6df7fbb80e67
Create Date: 2026-04-01 19:31:19.991280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b3332c5d429'
down_revision: Union[str, Sequence[str], None] = '6df7fbb80e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('thread_last_activity_fkey'), 'thread', type_='foreignkey')
    op.drop_constraint(op.f('topic_last_thread_id_fkey'), 'topic', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('topic_last_thread_id_fkey'), 'topic', 'thread', ['last_thread_id'], ['thread_id'])
    op.create_foreign_key(op.f('thread_last_activity_fkey'), 'thread', 'reply', ['last_activity'], ['reply_id'])
    # ### end Alembic commands ###