"""fixed cycles in Topic and Thread

Revision ID: ce7e24854037
Revises: 63c181282826
Create Date: 2026-04-01 21:27:10.274875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce7e24854037'
down_revision: Union[str, Sequence[str], None] = '63c181282826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('thread_last_activity_fkey'), 'thread', type_='foreignkey')
    op.drop_constraint(op.f('topic_last_thread_id_fkey'), 'topic', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('topic_last_thread_id_fkey'), 'topic', 'thread', ['last_thread_id'], ['thread_id'])
    op.create_foreign_key(op.f('thread_last_activity_fkey'), 'thread', 'reply', ['last_activity'], ['reply_id'])
    # ### end Alembic commands ###