"""Create rejected users table

Revision ID: cfa55e69c0d9
Revises: 937ffa3d466e
Create Date: 2026-04-04 21:00:51.493549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfa55e69c0d9'
down_revision: Union[str, Sequence[str], None] = '937ffa3d466e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('join_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('request', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_rejected_user_email'), 'rejected_user', ['email'], unique=True)
    op.create_index(op.f('ix_rejected_user_username'), 'rejected_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rejected_user_username'), table_name='rejected_user')
    op.drop_index(op.f('ix_rejected_user_email'), table_name='rejected_user')
    op.drop_table('rejected_user')
    # ### end Alembic commands ###