"""Added rejection date to rejection table

Revision ID: ff62ee008645
Revises: cfa55e69c0d9
Create Date: 2026-04-05 13:41:46.440465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff62ee008645'
down_revision: Union[str, Sequence[str], None] = 'cfa55e69c0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rejected_user', sa.Column('rejected_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rejected_user', 'rejected_date')
    # ### end Alembic commands ###